---
# find a way to use this in vars
docker_version: 28.0.4

# rocky versions sample:
# docker-ce-cli-1:{{ docker_version }}-1.el{{ ansible_distribution_major_version }}
# docker-ce-3:{{ docker_version }}-1.el{{ ansible_distribution_major_version }}
# ubuntu version sample:
# docker-ce=5:{{ docker_version }}-1~ubuntu.22.04~jammy
# docker-ce-cli=5:{{ docker_version }}-1~ubuntu.22.04~jammy
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_required_python_packages:
  - python3
  - python3-docker

docker_daemon_options: {"live_restore": true, "experimental": false}
