---
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
