---
- name: Copy ssh banner
  ansible.builtin.copy:
    src: banner.net
    dest: "{{ ssh_banner }}"
    owner: root
    group: root
    mode: "0644"
  when: ssh_banner != 'none'
  tags:
    - ssh

- name: Copy ssh config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config.d/00-ansible-ssh.conf
    owner: root
    group: root
    mode: "0600"
  tags:
    - ssh

- name: Test ssh configuration
  ansible.builtin.command: sshd -t
  register: sshd_test
  ignore_errors: true
  changed_when: false
  tags:
    - ssh

- name: Fail if ssh configuration is invalid
  ansible.builtin.fail:
    msg: "Invalid ssh configuration. Check the output of 'sshd -t'."
  when: sshd_test.rc != 0
  tags:
    - ssh

- name: Restart ssh service
  ansible.builtin.service:
    name: sshd
    state: restarted
    enabled: true
  changed_when: false
  when: sshd_test.rc == 0
  tags:
    - ssh

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: "{{ lookup('file', role_path + '/files/' + item + '.pub') }}"
  loop: "{{ ssh_users }}"
  tags:
    - ssh
    - publickey
