---
- name: Create a new user
  ansible.builtin.user:
    name: "{{ admin_user }}"
    comment: "Admin user"
    shell: /bin/bash
    create_home: true
  tags:
    - users

- name: Allow passwordless sudo for the user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ admin_user }}
    state: present
    line: "{{ admin_user }} ALL=(ALL) NOPASSWD:ALL"
    create: true
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - users
