---
- name: Remove conflicting packages before installing docker
  ansible.builtin.package:
    name: "{{ docker_conflicting_packages }}"
    state: absent
  tags:
    - prepare

- name: Install required python packages for docker tasks
  ansible.builtin.package:
    name: "{{ docker_required_python_packages }}"
    state: present
    update_cache: true
  tags:
    - prepare
    - python

- name: Install required packages for docker
  ansible.builtin.package:
    name: "{{ docker_required_packages }}"
    state: present
    update_cache: true
  tags:
    - prepare

- name: Prepare docker repository
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}_repo.yml"
  tags:
    - prepare
    - repo

- name: Set docker packages specific versions (only first two)
  ansible.builtin.set_fact:
    docker_packages: >-
      {{
        [
          docker_packages[0] ~ ( '=' if ansible_distribution == 'Ubuntu' else '-' ) ~ docker_versions_raw.results[0].stdout,
          docker_packages[1] ~ ( '=' if ansible_distribution == 'Ubuntu' else '-' ) ~ docker_versions_raw.results[1].stdout
        ]
        + docker_packages[2:]
      }}
  when: docker_version is defined and docker_version != "latest"
  tags:
    - prepare
