---
- name: Os hardening
  hosts: all
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding.
      net.ipv4.ip_forward: 1
    ssh_permit_root_login: "yes"
    ssh_server_password_login: "yes"
    # sshd_authenticationmethods: 'publickey,password'
